import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './component/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-zinc-800'>
      <body className={`p-5 h-screen ${inter.className}`} id="dark">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
